# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
library(bsicons)
library(bslib)
library(dplyr)
library(echarts4r)
library(glue)
library(htmlwidgets)
library(leaflet)
library(purrr)
library(reactable)
library(rhino)
library(sf)
library(treesitter)
library(treesitter.r)
library(usethis)
